# 前端项目部署到自建服务器 — 示例 workflow
# 用法：复制到你的前端项目根目录，并改名为 .github/workflows/deploy-frontend.yml
#
# 在 GitHub 仓库 Settings → Secrets 中需配置：
#   SSH_PRIVATE_KEY  部署用私钥全文（含 -----BEGIN/END-----）
#   SERVER_HOST      服务器 IP 或域名
#   SERVER_USER      SSH 登录用户名（如 root、deploy）
#   SERVER_DIR       服务器上静态文件目录（如 /var/www/my-app）
#
# 若项目用 npm：删掉「安装 pnpm」步骤，cache 改为 npm，install/build 改为 npm ci、npm run build
# 若构建产物在 build/：把下面 rsync 的 ./dist/ 改为 ./build/

name: 构建并部署前端

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 安装 Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 构建
        run: pnpm build

      - name: 配置 SSH 并同步到服务器
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_DIR: ${{ secrets.SERVER_DIR }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
          rsync -avz --delete -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            ./dist/ \
            "$SERVER_USER@$SERVER_HOST:$SERVER_DIR/"
